import type { DailyIdeaCategory, DailyIdeaFocus, GeneratedDailyIdea } from "./daily-ideas-core";

type FallbackSeed = Omit<
  GeneratedDailyIdea,
  "generatedAt" | "status" | "opportunity" | "creatorType" | "source" | "createdBy"
>;

const seeds: FallbackSeed[] = [
  {
    id: "fallback-ai-agent-briefs",
    title: "AI Client Brief Normalizer",
    summary: "Turn messy client messages, voice notes, and intake forms into a clean project brief with scope, risks, and next actions.",
    problem: "Freelancers and small agencies lose time converting scattered client input into an actionable scope.",
    solution: "A lightweight intake workspace that summarizes client material into a structured brief and flags missing decisions before work starts.",
    targetAudience: ["Freelancers", "Small agencies", "Consultants"],
    whyNow: "AI extraction is good enough to remove repetitive intake work while keeping a human approval step before commitments are made.",
    category: "ai",
    tags: ["AI", "Automation", "Agencies"],
    monetization: ["Monthly subscription", "Per-workspace team plan"],
    mvpFeatures: ["Paste or upload intake", "Structured brief", "Missing-info checklist", "Export to Markdown/PDF"],
    difficulty: "Starter",
    estimatedStartupCost: "Low — hosting plus model usage",
    estimatedBuildScope: "Weekend prototype; 2–4 weeks for team workflows",
    opportunityScore: 8.1,
    risks: ["Incorrect scope extraction", "Sensitive client data handling"],
    validationSteps: ["Interview 5 freelancers", "Process 20 historical briefs", "Measure editing time saved"],
    firstAction: "Collect five anonymized messy client requests and define the exact brief schema they should become.",
  },
  {
    id: "fallback-solana-wallet-alerts",
    title: "Solana Wallet Change Alerts for Teams",
    summary: "Watch treasury and operational wallets for high-signal balance, authority, and transaction changes and route alerts to the right operator.",
    problem: "Small Web3 teams often notice important wallet activity late because monitoring is scattered across explorers and chat channels.",
    solution: "A focused alert service that watches approved Solana addresses and emits human-readable notifications for configurable events.",
    targetAudience: ["Solana startups", "DAOs", "Treasury operators"],
    whyNow: "More teams operate directly on-chain, but many still rely on manual explorer checks for operational awareness.",
    category: "solana",
    tags: ["Solana", "Wallets", "Monitoring"],
    monetization: ["Subscription by wallet count", "Team alerting plan"],
    mvpFeatures: ["Wallet watchlist", "Balance-change alerts", "Large-transfer alerts", "Telegram/Slack delivery"],
    difficulty: "Intermediate",
    estimatedStartupCost: "Low to moderate — RPC/webhook usage and hosting",
    estimatedBuildScope: "1–2 week MVP",
    opportunityScore: 8.2,
    risks: ["Noisy alerts", "RPC provider dependency"],
    validationSteps: ["Interview 5 Solana operators", "Run shadow alerts on public wallets", "Measure alert precision"],
    firstAction: "Write the five wallet events that would justify waking up an operator.",
  },
  {
    id: "fallback-web3-proof-receipts",
    title: "Portable Proof-of-Work Receipts",
    summary: "Create simple signed receipts for completed digital work so freelancers and clients can preserve verifiable delivery history without exposing private files.",
    problem: "Freelancers building on-chain reputation need proof that work happened without publishing confidential deliverables.",
    solution: "Generate a minimal receipt containing parties, timestamp, work category, optional hash, and signatures, then anchor only the verification data.",
    targetAudience: ["Web3 freelancers", "Marketplaces", "On-chain identity products"],
    whyNow: "Portable reputation is becoming more useful as users work across multiple wallets, communities, and marketplaces.",
    category: "web3",
    tags: ["Web3", "Reputation", "Identity"],
    monetization: ["API usage", "Marketplace integration fees"],
    mvpFeatures: ["Receipt builder", "Wallet signatures", "Verification page", "Privacy-safe metadata"],
    difficulty: "Intermediate",
    estimatedStartupCost: "Low",
    estimatedBuildScope: "1–2 week prototype",
    opportunityScore: 7.8,
    risks: ["Fake counterparties", "Overcomplicated on-chain storage"],
    validationSteps: ["Interview marketplace operators", "Test bilateral signing flow", "Validate privacy expectations"],
    firstAction: "Define the smallest receipt schema that proves completion without revealing the deliverable.",
  },
  {
    id: "fallback-saas-renewal-desk",
    title: "Renewal Desk for Tiny SaaS Teams",
    summary: "A lightweight renewal calendar that shows which subscriptions, vendor contracts, and customer commitments require action before money leaks.",
    problem: "Small software teams often manage renewals in email and spreadsheets, causing surprise charges and missed negotiation windows.",
    solution: "Centralize renewal dates, owners, notice periods, and decision checkpoints with simple reminders and savings tracking.",
    targetAudience: ["Bootstrapped SaaS teams", "Startup operators", "Fractional CFOs"],
    whyNow: "Teams are scrutinizing recurring software spend while still using fragmented tools to manage renewal decisions.",
    category: "saas",
    tags: ["SaaS", "Operations", "Finance"],
    monetization: ["Monthly workspace subscription"],
    mvpFeatures: ["Renewal calendar", "Owner assignment", "Notice-period reminders", "Savings notes"],
    difficulty: "Starter",
    estimatedStartupCost: "Very low",
    estimatedBuildScope: "Weekend MVP",
    opportunityScore: 7.7,
    risks: ["Crowded SaaS management market", "Low willingness to pay for basic reminders"],
    validationSteps: ["Interview 5 founders", "Import one real vendor spreadsheet", "Track avoided renewal spend"],
    firstAction: "Ask three founders for the spreadsheet or system they currently use to track software renewals.",
  },
  {
    id: "fallback-fintech-cashflow-calendar",
    title: "Cash-Flow Calendar for Solo Businesses",
    summary: "Convert recurring bills, invoices, and expected deposits into a simple forward-looking daily cash calendar for solo operators.",
    problem: "Small operators can be profitable on paper while still getting surprised by timing gaps between expenses and incoming payments.",
    solution: "A cash timing dashboard that forecasts the next 30–60 days from manually entered or imported obligations and receivables.",
    targetAudience: ["Freelancers", "Solo businesses", "Small service firms"],
    whyNow: "Cash timing matters more when operators juggle subscriptions, contractors, and irregular client payments.",
    category: "fintech",
    tags: ["FinTech", "Cash Flow", "Small Business"],
    monetization: ["Freemium subscription", "Accountant partner plan"],
    mvpFeatures: ["Recurring expense calendar", "Expected invoice dates", "Low-balance warnings", "Scenario toggle"],
    difficulty: "Starter",
    estimatedStartupCost: "Very low without bank integrations",
    estimatedBuildScope: "Weekend MVP; integrations later",
    opportunityScore: 7.9,
    risks: ["Users may expect accounting accuracy", "Bank integrations add compliance complexity"],
    validationSteps: ["Test with 10 real monthly cash schedules", "Measure forecast usefulness", "Avoid positioning as accounting advice"],
    firstAction: "Build the manual-entry version before touching bank integrations.",
  },
  {
    id: "fallback-local-review-recovery",
    title: "Local Review Recovery Queue",
    summary: "Help local businesses turn negative reviews into a trackable service-recovery workflow instead of one-off public replies.",
    problem: "Owners often respond to bad reviews publicly but fail to assign, resolve, and learn from the underlying customer problem.",
    solution: "Capture negative reviews into a private resolution queue with owner, status, follow-up date, and recurring issue tags.",
    targetAudience: ["Restaurants", "Barbershops", "Auto shops", "Local service businesses"],
    whyNow: "Public reviews directly affect local buying decisions, yet recovery is still usually handled ad hoc.",
    category: "local-business",
    tags: ["Local Business", "Reviews", "Customer Service"],
    monetization: ["Monthly per-location subscription"],
    mvpFeatures: ["Review import or paste", "Recovery queue", "Owner assignment", "Issue tags", "Follow-up reminders"],
    difficulty: "Starter",
    estimatedStartupCost: "Very low",
    estimatedBuildScope: "Weekend prototype",
    opportunityScore: 8.0,
    risks: ["Review platform API limitations", "Owners may not maintain the workflow"],
    validationSteps: ["Interview 5 local owners", "Manually process 30 reviews", "Track resolution rate"],
    firstAction: "Pick one business category and manually map ten negative reviews into recurring issue types.",
  },
  {
    id: "fallback-creator-sponsor-crm",
    title: "Sponsor Memory for Small Creators",
    summary: "A tiny CRM that remembers every sponsor conversation, promised deliverable, rate, and follow-up for creators who are too small for enterprise tooling.",
    problem: "Creators lose sponsorship opportunities because negotiations live across email, DMs, notes, and memory.",
    solution: "Provide a deal-centric sponsor tracker with contact history, quoted rates, deliverables, due dates, and renewal reminders.",
    targetAudience: ["Independent creators", "Podcasters", "Newsletter writers", "Small creator managers"],
    whyNow: "More creators monetize through direct brand deals before they have staff or formal sales operations.",
    category: "creator-economy",
    tags: ["Creators", "CRM", "Sponsorships"],
    monetization: ["Monthly creator subscription"],
    mvpFeatures: ["Sponsor pipeline", "Rate history", "Deliverable checklist", "Follow-up reminders"],
    difficulty: "Starter",
    estimatedStartupCost: "Very low",
    estimatedBuildScope: "Weekend MVP",
    opportunityScore: 8.1,
    risks: ["Generic CRMs can substitute", "Email sync may expand scope"],
    validationSteps: ["Interview 5 creators", "Recreate their last 10 sponsor deals", "Measure missed follow-ups"],
    firstAction: "Ask three creators to show how they tracked their last sponsorship from first DM to payment.",
  },
  {
    id: "fallback-devtools-api-fixture",
    title: "API Failure Fixture Generator",
    summary: "Generate reusable mock responses for rate limits, malformed payloads, timeouts, and provider outages so small teams test failure paths before production does it for them.",
    problem: "Developers test happy paths thoroughly but often ship brittle integrations because realistic provider failures are cumbersome to reproduce.",
    solution: "A local-first fixture tool that wraps an endpoint and returns deterministic failure scenarios on demand.",
    targetAudience: ["API developers", "AI app teams", "Integration-heavy startups"],
    whyNow: "Apps increasingly depend on several external APIs, making graceful degradation a core product requirement rather than an edge case.",
    category: "developer-tools",
    tags: ["Developer Tools", "Testing", "Reliability"],
    monetization: ["Open-core with hosted team plan"],
    mvpFeatures: ["Failure scenario presets", "Custom status/body", "Latency injection", "Shareable fixture configs"],
    difficulty: "Intermediate",
    estimatedStartupCost: "Very low",
    estimatedBuildScope: "Weekend CLI prototype",
    opportunityScore: 8.3,
    risks: ["Developers can hand-roll mocks", "Needs excellent DX to stand out"],
    validationSteps: ["Test against three real integrations", "Measure setup time versus custom mocks", "Publish sample failure packs"],
    firstAction: "Implement four scenarios first: 429, 500, timeout, and invalid JSON.",
  },
  {
    id: "fallback-general-ops-inbox",
    title: "Decision Inbox for Small Teams",
    summary: "Turn loose questions from chat into a small queue of decisions with an owner, deadline, context, and final outcome.",
    problem: "Small teams lose important decisions inside chat threads, causing repeated debates and unclear ownership.",
    solution: "A minimal decision queue that captures a question, assigns a decider, attaches context, and records the final answer for later retrieval.",
    targetAudience: ["Startups", "Small remote teams", "Project-based businesses"],
    whyNow: "Teams move faster in chat, but chat remains a poor system of record for decisions that affect future work.",
    category: "general",
    tags: ["Productivity", "Teams", "Operations"],
    monetization: ["Monthly workspace subscription"],
    mvpFeatures: ["Decision capture", "Owner and deadline", "Context links", "Decision log"],
    difficulty: "Starter",
    estimatedStartupCost: "Very low",
    estimatedBuildScope: "Weekend MVP",
    opportunityScore: 7.8,
    risks: ["Teams may resist another workflow", "Can overlap with project tools"],
    validationSteps: ["Shadow one team for a week", "Capture repeated decisions", "Measure time spent re-litigating old choices"],
    firstAction: "Collect ten examples of decisions that were lost or repeated in chat.",
  },
  {
    id: "fallback-gwap-builder-brief",
    title: "GWAP Builder Brief Exchange",
    summary: "Turn promising Daily Ideas into standardized build briefs that can be handed to developers, agents, or Marketplace service providers without rewriting the concept from scratch.",
    problem: "Ideas often lose momentum between discovery and execution because the handoff to a builder lacks scope, acceptance criteria, and constraints.",
    solution: "Create a GWAP-native build brief from an idea with MVP scope, dependencies, success criteria, budget band, and recommended execution path.",
    targetAudience: ["GWAP OS users", "Founders", "Freelancers", "Marketplace builders"],
    whyNow: "The GWAP ecosystem already has discovery, identity, reputation, and marketplace surfaces that can converge around executable project briefs.",
    category: "gwap-ecosystem",
    tags: ["GWAP", "Marketplace", "Execution"],
    monetization: ["Marketplace conversion fee", "Premium project tooling"],
    mvpFeatures: ["Idea-to-brief conversion", "Acceptance criteria", "Budget band", "Marketplace handoff"],
    difficulty: "Intermediate",
    estimatedStartupCost: "Low — primarily product engineering",
    estimatedBuildScope: "1–2 week integrated MVP",
    opportunityScore: 8.8,
    risks: ["Brief quality must be consistent", "Marketplace supply must match project demand"],
    validationSteps: ["Convert 10 existing ideas into briefs", "Have 3 builders estimate them", "Measure clarification questions before work starts"],
    firstAction: "Define the exact build-brief schema shared by Daily Ideas and Tha GwapSpot Marketplace.",
  },
];

function materialize(seed: FallbackSeed): GeneratedDailyIdea {
  const generatedAt = "2026-08-16T00:00:00.000Z";
  return {
    ...seed,
    generatedAt,
    status: "generated",
    opportunity: seed.whyNow,
    creatorType: "ai",
    source: "ai",
    createdBy: "daily-ideas-engine",
  };
}

export function selectFallbackDailyIdea(
  category: DailyIdeaCategory,
  deliveredIds: ReadonlySet<string>,
  focus: DailyIdeaFocus | null,
) {
  const candidates = seeds
    .filter((seed) => seed.category === category || (category === "general" && seed.category !== "gwap-ecosystem"))
    .map(materialize);

  const unused = candidates.find((idea) => !deliveredIds.has(idea.id));
  if (unused) return unused;

  if (focus || category !== "general") {
    return seeds
      .filter((seed) => seed.category === "general")
      .map(materialize)
      .find((idea) => !deliveredIds.has(idea.id)) || null;
  }

  return null;
}
