"use client";
import { useMemo, useState } from "react";
import { useGwapOs } from "./os-provider";
import type { IdeaProject } from "../lib/os-state";
const fields:[keyof Pick<IdeaProject,"problem"|"targetUser"|"businessModel"|"technicalPlan"|"estimatedCost"|"mvpRoadmap"|"notes">,string,string][]=[
 ["problem","Problem","What exact pain or inefficiency are you solving?"],["targetUser","Target user","Who feels this problem most strongly?"],["businessModel","Business model","How could this create sustainable value or revenue?"],["technicalPlan","Technical plan","Core stack, integrations, data and architecture."],["estimatedCost","Estimated cost","MVP budget, infrastructure and major cost drivers."],["mvpRoadmap","MVP roadmap","Validation steps and the smallest credible launch sequence."],["notes","Research / notes","Evidence, assumptions, competitors, risks and open questions."],
];
export function IdeaLabView(){const {state,updateIdeaProject,removeIdeaProject,syncStatus}=useGwapOs();const [selectedId,setSelectedId]=useState(state.ideaProjects[0]?.id??"");const selected=useMemo(()=>state.ideaProjects.find(p=>p.id===selectedId)??state.ideaProjects[0]??null,[selectedId,state.ideaProjects]);
 if(!selected)return <div className="os-page os-runtime-page"><header className="os-runtime-heading"><span className="os-terminal-label">~/ideas/lab</span><h1>Idea Lab.</h1><p>Develop a saved Daily Idea into a concrete validation and MVP plan.</p></header><section className="os-runtime-panel"><h2>No active projects.</h2><p>Open Daily Ideas, save an opportunity, then choose Develop Idea to start its workspace.</p><a href="/app/ideas">Open Daily Ideas</a></section></div>;
 return <div className="os-page os-runtime-page"><header className="os-runtime-heading"><span className="os-terminal-label">~/ideas/lab · {syncStatus}</span><h1>Idea Lab.</h1><p>Move an opportunity from interesting to executable. The workspace saves into your GWAP OS account.</p></header><section className="os-runtime-grid"><aside className="os-runtime-panel os-runtime-note"><span className="os-terminal-label">PROJECTS · {state.ideaProjects.length}/8</span>{state.ideaProjects.map(p=><button key={p.id} type="button" onClick={()=>setSelectedId(p.id)} aria-pressed={p.id===selected.id}><strong>{p.title}</strong><br/><small>{p.status}</small></button>)}</aside><article className="os-runtime-panel"><div className="os-console-chrome"><span>idea-lab.workspace</span><span>{selected.status.toUpperCase()}</span></div><label>Project title<input value={selected.title} maxLength={120} onChange={e=>updateIdeaProject(selected.id,{title:e.target.value})}/></label><label>Status<select value={selected.status} onChange={e=>updateIdeaProject(selected.id,{status:e.target.value as IdeaProject["status"]})}><option>Exploring</option><option>Validating</option><option>Building</option></select></label>{fields.map(([key,label,placeholder])=><label key={key}>{label}<textarea value={selected[key]} placeholder={placeholder} rows={key==="technicalPlan"||key==="mvpRoadmap"?6:4} onChange={e=>updateIdeaProject(selected.id,{[key]:e.target.value})}/></label>)}<button type="button" onClick={()=>{removeIdeaProject(selected.id);setSelectedId("")}}>Archive project</button></article></section></div>;
}
