"use client";
import { usePrivy } from "@privy-io/react-auth";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { areGwapOsStatesEqual, createDefaultGwapOsState, GWAP_OS_STORAGE_KEY, normalizeGwapOsState, type DailyIdea, type IdeaProject, type MarketplaceIntent, type MarketplaceRole, type GnsIdentity, type GwapAccount, type GwapOsState, type GwapProfile, type GwapSettings } from "../lib/os-state";
type SyncStatus = "idle" | "saving" | "saved" | "error";
function readPendingState(){try{return window.localStorage.getItem(GWAP_OS_STORAGE_KEY)}catch{return null}}
function writePendingState(state:GwapOsState){try{window.localStorage.setItem(GWAP_OS_STORAGE_KEY,JSON.stringify(state))}catch{}}
function clearPendingState(){try{window.localStorage.removeItem(GWAP_OS_STORAGE_KEY)}catch{}}
type OsContextValue={account:GwapAccount;gnsIdentity:GnsIdentity;migrationAvailable:boolean;retrySync:()=>void;state:GwapOsState;syncStatus:SyncStatus;keepAccountState:()=>void;migrateLocalState:()=>void;updateProfile:(profile:Omit<GwapProfile,"updatedAt">)=>void;updateSettings:(settings:Partial<GwapSettings>)=>void;toggleFavorite:(slug:string)=>void;recordLaunch:(slug:string)=>void;saveIdea:(idea:DailyIdea)=>void;removeIdea:(id:string)=>void;startIdeaProject:(idea:DailyIdea)=>string;updateIdeaProject:(id:string,project:Partial<Omit<IdeaProject,"id"|"ideaId"|"createdAt">>)=>void;removeIdeaProject:(id:string)=>void;createMarketplaceIntent:(projectId:string,role:MarketplaceRole)=>string;updateMarketplaceIntent:(id:string,intent:Partial<Omit<MarketplaceIntent,"id"|"projectId"|"createdAt">>)=>void;removeMarketplaceIntent:(id:string)=>void;resetWorkspace:()=>void;updateGnsIdentity:(identity:Partial<GnsIdentity>)=>void};
const OsContext=createContext<OsContextValue|null>(null);
export function GwapOsProvider({account,children,gnsIdentity,hasCloudState,initialState}:{account:GwapAccount;children:ReactNode;gnsIdentity:GnsIdentity;hasCloudState:boolean;initialState:GwapOsState}){
 const {getAccessToken}=usePrivy();const [state,setState]=useState(initialState);const [identityOverride,setIdentityOverride]=useState<Partial<GnsIdentity>>({});const [migrationAvailable,setMigrationAvailable]=useState(false);const [syncStatus,setSyncStatus]=useState<SyncStatus>(hasCloudState?"saved":"idle");const stateRef=useRef(state);const migrationRef=useRef(false);const timerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const saveQueueRef=useRef<Promise<void>>(Promise.resolve());
 const updateState=useCallback((next:GwapOsState)=>{stateRef.current=next;setState(next)},[]);const updateGnsIdentity=useCallback((identity:Partial<GnsIdentity>)=>setIdentityOverride(c=>({...c,...identity})),[]);
 const authenticatedFetch=useCallback(async(input:RequestInfo|URL,init?:RequestInit)=>{const token=await getAccessToken();const headers=new Headers(init?.headers);if(token)headers.set("Authorization",`Bearer ${token}`);return fetch(input,{...init,headers,credentials:"same-origin"})},[getAccessToken]);
 const saveNow=useCallback((next:GwapOsState)=>{setSyncStatus("saving");const operation=saveQueueRef.current.catch(()=>undefined).then(async()=>{const response=await authenticatedFetch("/api/os-state",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:next})});if(!response.ok)throw new Error("Workspace sync failed");if(areGwapOsStatesEqual(stateRef.current,next)){clearPendingState();setSyncStatus("saved")}});saveQueueRef.current=operation;void operation.catch(()=>{if(areGwapOsStatesEqual(stateRef.current,next))setSyncStatus("error")})},[authenticatedFetch]);
 const scheduleSave=useCallback((next:GwapOsState)=>{writePendingState(next);if(timerRef.current)clearTimeout(timerRef.current);setSyncStatus("saving");timerRef.current=setTimeout(()=>saveNow(next),450)},[saveNow]);
 useEffect(()=>{const t=window.setTimeout(()=>{try{const stored=readPendingState();if(!stored)return;const local=normalizeGwapOsState(JSON.parse(stored) as unknown);if(!areGwapOsStatesEqual(local,initialState)){migrationRef.current=true;setMigrationAvailable(true);updateState(local)}else clearPendingState()}catch{clearPendingState()}},0);return()=>window.clearTimeout(t)},[initialState,updateState]);useEffect(()=>()=>{if(timerRef.current)clearTimeout(timerRef.current)},[]);useEffect(()=>{document.documentElement.dataset.gwapCompact=String(state.settings.compactMode);document.documentElement.dataset.gwapReduceMotion=String(state.settings.reduceMotion)},[state.settings.compactMode,state.settings.reduceMotion]);
 const commit=useCallback((next:GwapOsState)=>{updateState(next);if(migrationRef.current){writePendingState(next);return}scheduleSave(next)},[scheduleSave,updateState]);
 const migrateLocalState=useCallback(()=>{migrationRef.current=false;setMigrationAvailable(false);saveNow(stateRef.current)},[saveNow]);const keepAccountState=useCallback(()=>{migrationRef.current=false;setMigrationAvailable(false);clearPendingState();updateState(initialState);setSyncStatus(hasCloudState?"saved":"idle")},[hasCloudState,initialState,updateState]);
 const updateProfile=useCallback((profile:Omit<GwapProfile,"updatedAt">)=>{const c=stateRef.current;commit({...c,profile:{...profile,primaryWallet:account.verifiedWallet,updatedAt:new Date().toISOString()}})},[account.verifiedWallet,commit]);const updateSettings=useCallback((settings:Partial<GwapSettings>)=>{const c=stateRef.current;commit({...c,settings:{...c.settings,...settings}})},[commit]);const toggleFavorite=useCallback((slug:string)=>{const c=stateRef.current;commit({...c,favorites:c.favorites.includes(slug)?c.favorites.filter(x=>x!==slug):[slug,...c.favorites]})},[commit]);const recordLaunch=useCallback((slug:string)=>{const c=stateRef.current;commit({...c,recent:[{slug,openedAt:new Date().toISOString()},...c.recent.filter(x=>x.slug!==slug)].slice(0,8)})},[commit]);
 const saveIdea=useCallback((idea:DailyIdea)=>{const c=stateRef.current;commit({...c,ideas:[idea,...c.ideas.filter(x=>x.id!==idea.id)].slice(0,12)})},[commit]);const removeIdea=useCallback((id:string)=>{const c=stateRef.current;commit({...c,ideas:c.ideas.filter(x=>x.id!==id)})},[commit]);
 const startIdeaProject=useCallback((idea:DailyIdea)=>{const c=stateRef.current;const existing=c.ideaProjects.find(p=>p.ideaId===idea.id);if(existing)return existing.id;const now=new Date().toISOString();const id=crypto.randomUUID();const project:IdeaProject={id,ideaId:idea.id,title:idea.title,status:"Exploring",problem:idea.problem,targetUser:"",businessModel:"",technicalPlan:"",estimatedCost:"",mvpRoadmap:"",notes:idea.opportunity,createdAt:now,updatedAt:now};commit({...c,ideaProjects:[project,...c.ideaProjects].slice(0,8)});return id},[commit]);
 const updateIdeaProject=useCallback((id:string,patch:Partial<Omit<IdeaProject,"id"|"ideaId"|"createdAt">>)=>{const c=stateRef.current;commit({...c,ideaProjects:c.ideaProjects.map(p=>p.id===id?{...p,...patch,updatedAt:new Date().toISOString()}:p)})},[commit]);
 const removeIdeaProject=useCallback((id:string)=>{const c=stateRef.current;commit({...c,ideaProjects:c.ideaProjects.filter(p=>p.id!==id),marketplaceIntents:c.marketplaceIntents.filter(intent=>intent.projectId!==id)})},[commit]);
 const createMarketplaceIntent=useCallback((projectId:string,role:MarketplaceRole)=>{const c=stateRef.current;const project=c.ideaProjects.find(item=>item.id===projectId);if(!project)return "";const existing=c.marketplaceIntents.find(intent=>intent.projectId===projectId&&intent.role===role);if(existing){if(c.marketplaceIntents[0]?.id!==existing.id)commit({...c,marketplaceIntents:[existing,...c.marketplaceIntents.filter(intent=>intent.id!==existing.id)]});return existing.id}const now=new Date().toISOString();const id=crypto.randomUUID();const brief=[project.problem,project.targetUser?`Target user: ${project.targetUser}`:"",project.technicalPlan?`Technical direction: ${project.technicalPlan}`:""].filter(Boolean).join("\n\n").slice(0,1200);const intent:MarketplaceIntent={id,projectId,role,brief,budget:project.estimatedCost.slice(0,160),timeline:"",status:"Draft",createdAt:now,updatedAt:now};commit({...c,marketplaceIntents:[intent,...c.marketplaceIntents].slice(0,12)});return id},[commit]);
 const updateMarketplaceIntent=useCallback((id:string,patch:Partial<Omit<MarketplaceIntent,"id"|"projectId"|"createdAt">>)=>{const c=stateRef.current;commit({...c,marketplaceIntents:c.marketplaceIntents.map(intent=>intent.id===id?{...intent,...patch,updatedAt:new Date().toISOString()}:intent)})},[commit]);
 const removeMarketplaceIntent=useCallback((id:string)=>{const c=stateRef.current;commit({...c,marketplaceIntents:c.marketplaceIntents.filter(intent=>intent.id!==id)})},[commit]);
 const resetWorkspace=useCallback(()=>{migrationRef.current=false;setMigrationAvailable(false);updateState(createDefaultGwapOsState());clearPendingState();if(timerRef.current)clearTimeout(timerRef.current);setSyncStatus("saving");const operation=saveQueueRef.current.catch(()=>undefined).then(async()=>{const response=await authenticatedFetch("/api/os-state",{method:"DELETE"});if(!response.ok)throw new Error("Workspace reset failed");setSyncStatus("saved")});saveQueueRef.current=operation;void operation.catch(()=>setSyncStatus("error"))},[authenticatedFetch,updateState]);const retrySync=useCallback(()=>saveNow(stateRef.current),[saveNow]);
 const value=useMemo(()=>({account,createMarketplaceIntent,gnsIdentity:{...gnsIdentity,...identityOverride},keepAccountState,migrateLocalState,migrationAvailable,recordLaunch,removeIdea,removeIdeaProject,removeMarketplaceIntent,resetWorkspace,retrySync,saveIdea,startIdeaProject,state,syncStatus,toggleFavorite,updateIdeaProject,updateMarketplaceIntent,updateProfile,updateGnsIdentity,updateSettings}),[account,createMarketplaceIntent,gnsIdentity,identityOverride,keepAccountState,migrateLocalState,migrationAvailable,recordLaunch,removeIdea,removeIdeaProject,removeMarketplaceIntent,resetWorkspace,retrySync,saveIdea,startIdeaProject,state,syncStatus,toggleFavorite,updateIdeaProject,updateMarketplaceIntent,updateProfile,updateGnsIdentity,updateSettings]);return <OsContext.Provider value={value}>{children}</OsContext.Provider>;
}
export function useGwapOs(){const context=useContext(OsContext);if(!context)throw new Error("useGwapOs must be used inside GwapOsProvider");return context}
