"use client";

import { usePrivy } from "@privy-io/react-auth";
import { useCallback, useEffect, useState } from "react";

type ShareTheme = "green" | "red" | "blue" | "purple" | "silver" | "orange";
type PlatformConfig = { platform: "x"; label: string; officialHandle: string; verifierEnabled: boolean; verificationMethod: "public-post"; challengeTtlMinutes: number; shareThemes: ShareTheme[] };
type VerificationRecord = { platform: "x"; method: "public-post"; socialHandle: string; challengeCode: string | null; shareTheme: ShareTheme; status: "challenge-issued" | "awaiting-post" | "verified" | "revoked" | "expired"; issuedAt: string; expiresAt: string; verifiedAt: string | null; revokedAt: string | null; postUrl: string | null; postId: string | null };
type SocialVerificationPayload = { platforms: PlatformConfig[]; records: VerificationRecord[]; summary: { enabled: boolean; verifiedCount: number; pendingCount: number } };
const THEME_LABELS: Record<ShareTheme, string> = { green: "Neon Green", red: "Red", blue: "Electric Blue", purple: "Purple", silver: "White / Silver", orange: "Orange" };
function statusLabel(status: VerificationRecord["status"]) { if (status === "verified") return "VERIFIED"; if (status === "awaiting-post") return "POST SUBMITTED"; if (status === "challenge-issued") return "PUBLIC PROOF READY"; if (status === "expired") return "EXPIRED"; return "REVOKED"; }

export function SocialVerificationPanel() {
  const { getAccessToken } = usePrivy();
  const [payload, setPayload] = useState<SocialVerificationPayload | null>(null);
  const [handle, setHandle] = useState(""); const [selectedTheme, setSelectedTheme] = useState<ShareTheme>("green"); const [postUrl, setPostUrl] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [unavailable, setUnavailable] = useState(false);
  const authenticatedFetch = useCallback(async (input: RequestInfo | URL, init?: RequestInit) => { const token = await getAccessToken(); const headers = new Headers(init?.headers); if (token) headers.set("Authorization", `Bearer ${token}`); return fetch(input, { ...init, headers, credentials: "same-origin" }); }, [getAccessToken]);
  const load = useCallback(async () => { const response = await authenticatedFetch("/api/gwapscore/social-verification", { cache: "no-store" }); if (!response.ok) throw new Error("Verification status unavailable"); const next = (await response.json()) as SocialVerificationPayload; setPayload(next); setUnavailable(false); return next; }, [authenticatedFetch]);
  useEffect(() => { let active = true; const initial = window.setTimeout(() => { void load().catch(() => { if (active) setUnavailable(true); }); }, 0); return () => { active = false; window.clearTimeout(initial); }; }, [load]);
  const platform = payload?.platforms.find((item) => item.platform === "x") ?? null; const record = payload?.records.find((item) => item.platform === "x") ?? null; const pending = record?.status === "challenge-issued" || record?.status === "awaiting-post";
  const proofUrl = record?.challengeCode && typeof window !== "undefined" ? `${window.location.origin}/v/${encodeURIComponent(record.challengeCode)}?theme=${record.shareTheme}&card=4` : "";
  const shareText = record?.challengeCode && proofUrl ? [`Verifying control of @${record.socialHandle} with GWAP Public Proof @_GwapSpot.`, "", `GWAP Public Proof: ${record.challengeCode}`, "", "Build your digital trust ↓", proofUrl].join("\n") : "";
  function trackClient(event: string) { if (!record?.challengeCode) return; void fetch("/api/public-proof/analytics", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ event, challengeCode: record.challengeCode, theme: record.shareTheme }), keepalive: true }).catch(() => undefined); }
  async function action(body: Record<string, unknown>) { setBusy(true); setMessage(null); try { const response = await authenticatedFetch("/api/gwapscore/social-verification", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = (await response.json().catch(() => null)) as { error?: string } | null; if (!response.ok) throw new Error(result?.error || "Verification action failed"); await load(); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Verification action failed"); return false; } finally { setBusy(false); } }
  async function issueChallenge() { const ok = await action({ action: "issue", platform: "x", handle, shareTheme: selectedTheme }); if (ok) setHandle(""); }
  async function copySharePost() { if (!shareText) return; try { await navigator.clipboard.writeText(shareText); setMessage("Verification post copied. Publish it from the X account you are verifying."); } catch { setMessage("Copy failed. Select the verification post manually."); } }
  async function verifyPost() { const ok = await action({ action: "submit-post", platform: "x", postUrl }); if (ok) setPostUrl(""); }

  if (unavailable) return <section className="os-runtime-panel os-runtime-note" id="social-verification"><span className="os-terminal-label">GWAP PUBLIC PROOF</span><h2>Social verification is temporarily unavailable.</h2><p>This infrastructure state does not reduce your Trust Coverage or GwapScore.</p></section>;
  if (!payload || !platform) return <section className="os-runtime-panel os-runtime-note" id="social-verification" role="status"><span className="os-terminal-label">GWAP PUBLIC PROOF</span><h2>Loading social verification…</h2></section>;
  if (!platform.verifierEnabled) return <section className="os-runtime-panel os-runtime-note" id="social-verification"><span className="os-terminal-label">GWAP PUBLIC PROOF · STAGED</span><h2>Public-post verification is built and waiting for the X API credential.</h2><p>GWAP will independently read the submitted public post, confirm the exact challenge code, match the post author to the claimed handle, and bind the stable X account ID. A pasted URL alone can never create verification.</p></section>;
  if (record?.status === "verified") { const receiptUrl = record.challengeCode ? `/v/${encodeURIComponent(record.challengeCode)}?theme=${record.shareTheme}` : null; return <section className="os-runtime-panel os-runtime-note" id="social-verification"><span className="os-terminal-label">GWAP PUBLIC PROOF · VERIFIED</span><h2>@{record.socialHandle} is controlled by this GWAP account.</h2><p>GWAP independently retrieved the public X post, matched its author to @{record.socialHandle}, and observed the one-time challenge. The relationship now enters your Trust and Relationship Graphs with Proof-of-Control provenance.</p><div className="os-inline-actions">{receiptUrl ? <a href={receiptUrl}>Open verification receipt →</a> : null}{record.postUrl ? <a href={record.postUrl} target="_blank" rel="noreferrer">View proof post ↗</a> : null}<button className="os-secondary-action" type="button" disabled={busy} onClick={() => void action({ action: "revoke", platform: "x" })}>Revoke verification</button></div><p>You may delete the public challenge post after verification. GWAP retains the verification receipt and provenance state.</p>{record.verifiedAt ? <small>Verified {new Date(record.verifiedAt).toLocaleString()}</small> : null}{message ? <p className="os-registration-output">› {message}</p> : null}</section>; }
  if (pending && record?.challengeCode) { const composeUrl = `https://x.com/intent/post?text=${encodeURIComponent(shareText)}`; return <section className="os-runtime-panel os-runtime-note" id="social-verification" aria-live="polite"><span className="os-terminal-label">GWAP PUBLIC PROOF · {statusLabel(record.status)}</span><h2>Publish your one-time proof from @{record.socialHandle}.</h2><p>Your selected share theme is <strong>{THEME_LABELS[record.shareTheme]}</strong>. The GWAP link becomes the public verification receipt and branded share surface.</p><div className="os-identity-console"><div className="os-console-chrome"><span>PUBLIC POST CHALLENGE</span><span>EXPIRES IN {platform.challengeTtlMinutes} MIN</span></div><div className="os-identity-body"><div className="os-identity-copy"><span className="os-terminal-label">POST FROM @{record.socialHandle}</span><h2>{record.challengeCode}</h2><pre style={{ whiteSpace: "pre-wrap", font: "inherit" }}>{shareText}</pre></div></div></div><div className="os-inline-actions"><button className="os-secondary-action" type="button" onClick={() => void copySharePost()}>Copy verification post</button><a className="os-primary-action" href={composeUrl} target="_blank" rel="noreferrer" onClick={() => trackClient("x_composer_opened")}>Open X to post ↗</a></div><label className="os-field"><span>Paste your published X post URL</span><input value={postUrl} onChange={(event) => setPostUrl(event.target.value)} placeholder="https://x.com/yourhandle/status/…" autoComplete="off" inputMode="url" /></label><div className="os-inline-actions"><button className="os-primary-action" type="button" disabled={busy || !postUrl.trim()} onClick={() => void verifyPost()}>{busy ? "Checking post…" : "Verify public proof"}</button><button className="os-secondary-action" type="button" disabled={busy} onClick={() => void action({ action: "revoke", platform: "x" })}>Cancel challenge</button></div><p>GWAP verifies the post author, the exact challenge, and the stable X account ID. The share link itself is not proof.</p>{message ? <p className="os-registration-output">› {message}</p> : null}</section>; }
  return <section className="os-runtime-panel os-runtime-note" id="social-verification"><span className="os-terminal-label">GWAP PUBLIC PROOF · X</span><h2>Verify your X account and choose your share look.</h2><p>GWAP generates a one-time public challenge and branded verification link. Publish it from the account you control, then paste the post URL back here for independent verification.</p><label className="os-field"><span>X handle</span><input value={handle} onChange={(event) => setHandle(event.target.value)} placeholder="yourhandle" autoComplete="off" inputMode="text" /></label><div><span className="os-terminal-label">CHOOSE SHARE COLOR</span><div className="os-inline-actions" style={{ marginTop: 10 }}>{platform.shareThemes.map((theme) => <button key={theme} type="button" className={selectedTheme === theme ? "os-primary-action" : "os-secondary-action"} onClick={() => setSelectedTheme(theme)} aria-pressed={selectedTheme === theme}>{THEME_LABELS[theme]}</button>)}</div></div><div className="os-inline-actions"><button className="os-primary-action" type="button" disabled={busy || !handle.trim()} onClick={() => void issueChallenge()}>{busy ? "Creating Public Proof…" : "Generate Public Proof"}</button></div>{record?.status === "expired" ? <p>Your previous challenge expired. Generate a new one when ready.</p> : null}{record?.status === "revoked" ? <p>Your previous social verification was revoked.</p> : null}{message ? <p className="os-registration-output">› {message}</p> : null}</section>;
}
